// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tabintel/invoice-system/ent/invoiceitem"
	"github.com/Tabintel/invoice-system/ent/predicate"
)

// InvoiceItemUpdate is the builder for updating InvoiceItem entities.
type InvoiceItemUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceItemMutation
}

// Where appends a list predicates to the InvoiceItemUpdate builder.
func (iiu *InvoiceItemUpdate) Where(ps ...predicate.InvoiceItem) *InvoiceItemUpdate {
	iiu.mutation.Where(ps...)
	return iiu
}

// Mutation returns the InvoiceItemMutation object of the builder.
func (iiu *InvoiceItemUpdate) Mutation() *InvoiceItemMutation {
	return iiu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iiu *InvoiceItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, iiu.sqlSave, iiu.mutation, iiu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iiu *InvoiceItemUpdate) SaveX(ctx context.Context) int {
	affected, err := iiu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iiu *InvoiceItemUpdate) Exec(ctx context.Context) error {
	_, err := iiu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iiu *InvoiceItemUpdate) ExecX(ctx context.Context) {
	if err := iiu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iiu *InvoiceItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(invoiceitem.Table, invoiceitem.Columns, sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt))
	if ps := iiu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iiu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iiu.mutation.done = true
	return n, nil
}

// InvoiceItemUpdateOne is the builder for updating a single InvoiceItem entity.
type InvoiceItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceItemMutation
}

// Mutation returns the InvoiceItemMutation object of the builder.
func (iiuo *InvoiceItemUpdateOne) Mutation() *InvoiceItemMutation {
	return iiuo.mutation
}

// Where appends a list predicates to the InvoiceItemUpdate builder.
func (iiuo *InvoiceItemUpdateOne) Where(ps ...predicate.InvoiceItem) *InvoiceItemUpdateOne {
	iiuo.mutation.Where(ps...)
	return iiuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iiuo *InvoiceItemUpdateOne) Select(field string, fields ...string) *InvoiceItemUpdateOne {
	iiuo.fields = append([]string{field}, fields...)
	return iiuo
}

// Save executes the query and returns the updated InvoiceItem entity.
func (iiuo *InvoiceItemUpdateOne) Save(ctx context.Context) (*InvoiceItem, error) {
	return withHooks(ctx, iiuo.sqlSave, iiuo.mutation, iiuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iiuo *InvoiceItemUpdateOne) SaveX(ctx context.Context) *InvoiceItem {
	node, err := iiuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iiuo *InvoiceItemUpdateOne) Exec(ctx context.Context) error {
	_, err := iiuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iiuo *InvoiceItemUpdateOne) ExecX(ctx context.Context) {
	if err := iiuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iiuo *InvoiceItemUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceItem, err error) {
	_spec := sqlgraph.NewUpdateSpec(invoiceitem.Table, invoiceitem.Columns, sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt))
	id, ok := iiuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iiuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceitem.FieldID)
		for _, f := range fields {
			if !invoiceitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iiuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &InvoiceItem{config: iiuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iiuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iiuo.mutation.done = true
	return _node, nil
}
