// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Invoice is the predicate function for invoice builders.
type Invoice func(*sql.Selector)

// InvoiceItem is the predicate function for invoiceitem builders.
type InvoiceItem func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
